// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JBoLgOGiWKW9rJEuULB2txhU7VgdX78',
    appId: '1:971332768604:web:64d3e5fd846ea89295a799',
    messagingSenderId: '971332768604',
    projectId: 'flutter-signup-pro',
    authDomain: 'flutter-signup-pro.firebaseapp.com',
    storageBucket: 'flutter-signup-pro.appspot.com',
    measurementId: 'G-TK2M59B6WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMd4dtK1bpEe-s8HuRyGM-14HC7K_vBE',
    appId: '1:971332768604:android:fba8bb5c16b1c0c495a799',
    messagingSenderId: '971332768604',
    projectId: 'flutter-signup-pro',
    storageBucket: 'flutter-signup-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYdkQEYLCTlwrEcfVIsJmixCwSEca1-YI',
    appId: '1:971332768604:ios:c0a6a8c7969be81095a799',
    messagingSenderId: '971332768604',
    projectId: 'flutter-signup-pro',
    storageBucket: 'flutter-signup-pro.appspot.com',
    iosBundleId: 'com.example.projApp3',
  );
}
